# -*- coding: utf-8 -*-
"""PracticasUnidad1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inNayjJe3zcmHWR9KunA4yexk-wSDDaK
"""

#Practica_1
def calcular_producto(*args):
  """
  Calcula el producto de un número variable de argumentos numéricos.

  Args:
    *args: Una tupla de números.

  Returns:
    El producto de todos los números en la tupla.
    Devuelve 1 si no se proporciona ningún argumento.
  """
  producto = 1
  for numero in args:
    producto *= numero
  return producto

# Ejemplos de uso
print(calcular_producto(2, 3, 4))  # Salida: 24
print(calcular_producto(5, 10))    # Salida: 50
print(calcular_producto())         # Salida: 1
print(calcular_producto(1.5, 2.5)) # Salida: 3.75

#Practica_2
abecedario = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

# Eliminar letras en posiciones múltiplos de 3 (empezando desde 0)
for i in range(len(abecedario) - 1, -1, -1):
  if (i + 1) % 3 == 0:
    abecedario.pop(i)

# Mostrar la lista resultante
abecedario

#Practica_3
nombre_completo = input("Ingresa tu nombre completo: ")
nombre_invertido = ""
for letra in reversed(nombre_completo):
  nombre_invertido += letra
nombre_invertido

#Practica_4
def capturar_materias():
  """Captura las materias y créditos del semestre del usuario."""
  materias = {}
  semestre = int(input("Ingresa el semestre (inferior a 8vo): "))
  if semestre >= 8:
    print("El semestre debe ser inferior a 8vo.")
    return None, 0  # Regresa None para indicar un error
  while True:
    asignatura = input("Ingresa el nombre de la asignatura (o escribe 'fin' para terminar): ")
    if asignatura.lower() == 'fin':
      break
    try:
      creditos = int(input(f"Ingresa los créditos de {asignatura}: "))
      materias[asignatura] = creditos
    except ValueError:
      print("Número de créditos inválido. Intenta de nuevo.")
  total_creditos = sum(materias.values())
  return materias, total_creditos
# Ejemplo de uso
materias, total_creditos = capturar_materias()
if materias:
  print("\nMaterias y créditos del semestre:")
  for asignatura, creditos in materias.items():
      print(f'"{asignatura}" tiene "{creditos}" créditos.')
  print(f"\nTotal de créditos del semestre: {total_creditos}")

#Practica_5
def imprimir_pares_llave_valor(**kwargs):
  """
  Recibe n parámetros de llave-valor e imprime la información en formato "{llave}": "{Valor}".
  Args:
    **kwargs: Un diccionario de argumentos de palabra clave.
  """
  for llave, valor in kwargs.items():
    print(f'"{llave}": "{valor}"')
# Ejemplo de uso
imprimir_pares_llave_valor(nombre="Juan", apellido="Pérez", edad=30, ciudad="Madrid")

#Practica_6
numeros = ["cero", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez", "once", "doce", "trece", "catorce", "quince", "dieciséis", "diecisiete", "dieciocho", "diecinueve", "veinte"]
numero = int(input("Introduce un numero entre 0 y 20: "))
numeros[numero]

#Practica_7
from datetime import datetime

def imprimir_fecha():
  """Muestra un menú y la fecha en el formato seleccionado."""

  while True:
    print("\nMenú de opciones:")
    print("1.- Imprimir YYYY/MM/DD")
    print("2.- Imprimir MM/DD/YYYY")
    opcion = input("Selecciona una opción (1 o 2): ")

    if opcion == '1':
      fecha_actual = datetime.now().strftime("%Y/%m/%d")
      print("Fecha actual (YYYY/MM/DD):", fecha_actual)
      break
    elif opcion == '2':
      fecha_actual = datetime.now().strftime("%m/%d/%Y")
      print("Fecha actual (MM/DD/YYYY):", fecha_actual)
      break
    else:
      print("Opción no válida. Intenta de nuevo.")

imprimir_fecha()